name: Deploy Node Application

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            #BACKEND
            - name: Login Dockerhub
              env:
                  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
                  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
              run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

            - name: Build the Docker image
              run: docker build -t gayan65/sylox_frontend:latest .

            - name: Push to docker hub
              run: docker push gayan65/sylox_frontend:latest

    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull image from Docker Hub
              run: docker pull gayan65/sylox_frontend:latest

            - name: Delete old container
              run: docker rm -f reactjs-app-container || true

            - name: Run Docker Container
              shell: bash
              run: |
                  sudo docker run -d -p 3000:80 --name reactjs-app-container \
                  gayan65/sylox_frontend
